version: "3.0"
services:
  app: 
    build:
      context: .
    ports: 
      - "9095:9095"
    depends_on: 
      - postgres
      - kafka
    environment:
      - POSTGRESQL_URL=jdbc:postgresql://localhost:5432/test
      - DATASOURCE_USERNAME=moelsaeed
      - DATASOURCE_PASSWORD=messi
  kafka: 
    image: johnnypark/kafka-zookeeper
    ports: 
      - 9092:9092
      - 2181:2181
    environment: 
      - ADVERTISED_HOST=127.0.0.1
      - NUM_PARTITIONS=10
  postgres: 
    image: postgres
    expose: 
      - 5432
    ports: 
      - 5432:5432
    environment: 
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=messi
      - POSTGRES_USER=moelsaeed
      - POSTGRES_DB=test
    volumes: 
      - POSTGRESDATA:/var/lib/postgresql/data
volumes:
  POSTGRESDATA