spring:
  application:
    name: backend-challenge
  #kafka
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      bootstrap-servers: http://127.0.0.1:9092
    listener:
      missing-topics-fatal: false

server:
  port: 9050

#OpenAPI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true



